### ISSUE TITLE
[NonoDailyCardGame] 무한 루프 현상이 있는걸로 보입니다.

### ISSUE THREAD

**Issue by MPThLee** [ggomdyu/DailyCheck-In#1]
![image](https://user-images.githubusercontent.com/26970092/94341379-caca5a80-0043-11eb-90c5-bdd57952c288.png)
![image](https://user-images.githubusercontent.com/26970092/94341395-e0d81b00-0043-11eb-8f76-cacaa6d42422.png)

현재 출력 상황으로는 어디서 어떤 문제가 있는지는 모르겠습니다만, 아마도 로그인 캡챠를 solve 못해서 생긴 문제로 보이네요...

**Comment by ggomdyu** [comment]
제보 감사합니다. 저도 확인해보니 무한 루프 문제가 가끔 발생하고 있었네요.. 곧 수정하도록 하겠습니다...

**Comment by MPThLee** [comment]
일단 다른 action 을 사용해서 임시로 고쳐봤습니다.
```yml
- name: Run check-in
  uses: nick-invision/retry@v1
  if: ${{ always() }}
  with:
    timeout_minutes: 2
    max_attempts: 6
    command: cd Konami/NonoDailyCardGame/NonoDailyCardGame/ && dotnet run <id> <pass>
```

timeout 기능이 작동할지는 미지수인데 일단 workaround 정도로...
